name: Linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/setup-node@v4
      with:
          node-version: 20
    - run: npm install
    - name: Get list of changed JavaScript files
      id: changed-files
      run: |
        echo "files=$(git diff --name-only origin/main...HEAD -- '*.js')"  >> $GITHUB_OUTPUT
    - name: Run ESLint on changed files
      if: steps.changed-files.outputs.files != ''
      run: |
        npx eslint ${{ steps.changed-files.outputs.files }}
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
