name: Linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/setup-node@v4
      with:
          node-version: 20
    - run: yarn install
    - uses: sibiraj-s/action-eslint@v3
      with:
        eslint-args: '--ignore-path=.gitignore --quiet'
        extensions: 'js'
        annotations: true
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
